import chromadb
from typing import List, Dict, Any

class VectorStore:
    """
    Manages persistent storage and retrieval of embedded knowledge chunks using ChromaDB.
    Ensures idempotency by utilizing deterministic chunk IDs.
    """
    
    DEFAULT_PERSIST_DIRECTORY = "data/chroma_db"
    DEFAULT_COLLECTION_NAME = "study_documents"

    def __init__(
        self,
        persist_directory: str = DEFAULT_PERSIST_DIRECTORY,
        collection_name: str = DEFAULT_COLLECTION_NAME,
    ):
        self.persist_directory = persist_directory
        self.collection_name = collection_name

        self.client = chromadb.PersistentClient(path=self.persist_directory)

        self.collection = self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={"hnsw:space": "cosine"} # Proper ChromaDB metadata configuration syntax
        )

    def add_documents(
        self,
        documents: List[Dict[str, Any]],
        embeddings: List[List[float]],
    ) -> None:
        """
        Upsert documents into ChromaDB. Uses deterministic chunk_ids to prevent duplicates.
        """
        if len(documents) != len(embeddings):
            raise ValueError("Dimension mismatch: Number of documents must exactly match the number of embeddings.")

        if not documents:
            return

        # Extract deterministic IDs generated by the TextChunker in Phase 1
        try:
            ids = [doc["chunk_id"] for doc in documents]
        except KeyError:
            raise ValueError("All documents must contain a 'chunk_id' key generated by the TextChunker.")

        # Support both 'text' and 'content' keys dynamically
        texts = [doc.get("text") or doc.get("content", "") for doc in documents]
        metadatas = [doc.get("metadata", {}) for doc in documents]

        # Use upsert instead of add to gracefully handle existing documents without throwing errors
        self.collection.upsert(
            ids=ids,
            documents=texts,
            embeddings=embeddings,
            metadatas=metadatas,
        )

    def search(
        self,
        query_embedding: List[float],
        top_k: int = 5,
    ) -> Dict[str, Any]:
        """
        Execute a nearest-neighbor vector search.
        """
        if top_k <= 0:
            raise ValueError("top_k must be strictly positive.")

        return self.collection.query(
            query_embeddings=[query_embedding],
            n_results=top_k,
        )

    def count(self) -> int:
        """
        Return the total number of chunks currently indexed in the collection.
        """
        return self.collection.count()